# Generated by Django 4.2.4 on 2023-09-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='nome_fantasia',
        ),
    ]
