export * from "./login/login.tsx"
export * from "./home/home.tsx"
export * from "./registro/registro.tsx"
export * from "./registroCliente/registroCliente.tsx"
export * from "./registroPrestador/registroPrestador.tsx"
export * from "./agendar/agendar.tsx"